# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: Coding Skyscrapers
url:   http://codingskyscrapers.com
author:
  name:    Matt West        # For copyright notice and ATOM feeds
  email:   matt.west@kojilabs.com # Exception emails will go here, and it is used in ATOM feeds
  open_id:                  # These are used to login to the admin area
      - https://plus.google.com/103780700566333678292/posts
      - https://profiles.google.com/103780700566333678292
